    <p style='text-align:right;margin-bottom:18.0pt'><b><span style='font-size:10.0pt;font-family:
"Arial",sans-serif'>Source:</span></b><span style='font-size:10.0pt;font-family:
"Arial",sans-serif'> Ana de Almeida, João Cordeiro, Alberto Vilas</span></p>

<header style='background-color:#3498DB;padding:18.0px;text-align:center;font-size:22px;color:white;font-family:"Arial",sans-serif'>
<h2>Iscte – Instituto Universitário de Lisboa </h2>
<h2><span style='font-size:20.0pt'>Desenho e Analise de Algoritmos (2023/2024)</span></h2>
</header>

# Breve introdução ao módulo numpy

Este notebook contém alguns exemplos básicos de utilização do módulo numpy.

Para começar, basta experimentar executar as células seguintes.


<font size="4"> <div class="alert alert-success" role="alert"> 
### Para executar uma célula, basta clicar Shift+Enter.
</div></font>

In [1]:
#importar a biblioteca numérica numpy e criar um alias curto
import numpy as np

In [2]:
new_arr = np.array([1, 2, 3]) # cria um novo array de inteiros (ndarray)

new_arr

array([1, 2, 3])

In [3]:
#Note a diferença entre um print(new_arr) e a instrução anterior
print(new_arr)

[1 2 3]


In [4]:
new_arr2 = np.array([1, 2, 3.0]) # cria um novo array de floats
new_arr2

array([1., 2., 3.])

In [5]:
# Mais uma vez, note a diferença visual entre um print(new_arr) e a instrução anterior
print(new_arr2)

[1. 2. 3.]


In [8]:
new_a3 = np.zeros(5, dtype=int) # cria array de tamanho 5 com zeros inteiros
print(new_a3)

[0 0 0 0 0]


In [9]:
new_a3[0] = 3 # alteração de valor em indíce
new_a3

array([3, 0, 0, 0, 0])

In [10]:
new_a4 = np.ones(7, dtype=int) # cria array de tamanho 7 com 1s 
print(new_a4)

[1 1 1 1 1 1 1]


In [11]:
n = 10
new_a5 = np.arange(n) # cria array com inteiros de 0 a (n-1)
print(new_a5)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
i = 2
j = 3
step = 0.2
new_a6 = np.arange(i, j, step)  # cria array com floats (devido ao passo ser um float) de i a (j-1) com variação step 
new_a6

array([2. , 2.2, 2.4, 2.6, 2.8])

In [13]:
len(new_a6)

5

 >A estrutura de *array* é indexada a partir do **zero** e até **n-1** onde n = len(list). 

In [14]:
new_m = np.array([(1, 2), (3, 4)]) # cria um novo array de duas dimensões - matriz -de inteiros
new_m

array([[1, 2],
       [3, 4]])

>As funções de criação de matrizes 2D, por exemplo, numpy.zeros, numpy.eye, numpy.diag e numpy.vander, numpy.random definem propriedades de matrizes especiais representadas como matrizes 2D. Experimente-as...

In [15]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

>As funções de criação de ndarray, por exemplo, numpy.ones, numpy.zeros e random, definem arrays com base na forma desejada. 

In [16]:
np.ones((3, 2, 1)) # matriz 3-D (tensor); veja com atenção os índices...

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

>De seguida, são criadas 2 matrizes com valores aleatórios com as formas 2x2 e 2x4x3 (formas (2,3) e (2,4,3)), respetivamente. 
A semente é 45 para que possam replicar estes mesmos números pseudo-aleatórios:

In [17]:
#primeiro importar o módulo necessário
import numpy.random

#criar uma instância do gerador (seed igual a 45)
rng = np.random.default_rng(45)

#depois, criar as matrizes:
rng.random((2,2))

array([[0.57313066, 0.52849115],
       [0.76365024, 0.81169277]])

In [ ]:
rng.random((2,4,3))

In [ ]:
#agora uma matriz com valores aleatórios no intervalo [0,4[
rng.integers(0, 5, size=(2,3,4))

<font size="4"> <div class="alert alert-success" role="alert">
    Esta é uma boa altura para recordar que a documentação oficial para os módulos do *numpy*, pode ser encontrada em https://numpy.org/doc/stable/user/absolute_beginners.html
    
E, já agora, um livro on-line (Think Python 2, 2nd edition): http://greenteapress.com/thinkpython2/html/index.html
    
</div></font>

## Algoritmo mistério em Python

Siga as instruções de código seguintes e veja se consegue entender o que se passa. Vamos usar este código na próxima semana!

In [18]:
# Um algoritmo que ordena a list A
# Este código altera diretamente A
# Verifique que percebe como funciona!
def AlgoritmoMisterio(A):
    for i in range(1,len(A)):
        current = A[i]
        j = i-1
        while j >= 0 and A[j] > current:
            A[j+1] = A[j]
            j -= 1
        A[j+1] = current

In [19]:
# Vamos fazer um teste simples (controlado)
A = np.array([8,3,4,1,6,7,11,5])
print(A)
AlgoritmoMisterio(A)
print(A)

[ 8  3  4  1  6  7 11  5]
[ 1  3  4  5  6  7  8 11]


In [20]:
C=rng.permutation(A)
print(C)
AlgoritmoMisterio(C)
print(C)

[ 7  1  3  6  4  5  8 11]
[ 1  3  4  5  6  7  8 11]


In [21]:
# O Python tem métodos implementados para ordenar lists
A = [5,3,4,1,6]
A.sort()  # Python's built-in sort also sorts A in-place
print('Python sort in-place:', A)

# Se não quisermos alterar a list A, podemos resolver:
A = [5,3,4,1,6] # partir novamente de um A desordenado
B = A[:] # copia A para B
B.sort()
print('Python sort fazendo uma cópia:', B)

print('Input original:', A)

print(B)

#ou podemos usar a função sorted(), que funciona com qualquer iterável:
C = sorted(A)
print('Python sort sem alterar o input:', C)
print('Input original:', A)


Python sort in-place: [1, 3, 4, 5, 6]
Python sort fazendo uma cópia: [1, 3, 4, 5, 6]
Input original: [5, 3, 4, 1, 6]
[1, 3, 4, 5, 6]
Python sort sem alterar o input: [1, 3, 4, 5, 6]
Input original: [5, 3, 4, 1, 6]


In [33]:
def fiboR(n):
    if n==0 : return 0
    if n==1 : return 1
    return fiboR(n-2) + fiboR(n-1)
    
fiboR(5)

5